### ISSUE TITLE
Pod Install

### ISSUE THREAD

**Issue by alexandrenascimento** [vimeo/VIMNetworking#29]
It's possible use this library with pod install?
My project already uses pod install and when I add this library, crash with:

"(UIImageView+AFNetworking.o) ld: 76 duplicate symbols for architecture i386 clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Thanks!

**Comment by alexandrenascimento** [comment]
I think it is very simple... https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by alfiehanssen** [comment]
@alexandrenascimento thanks for writing, I'm probably going to add support for cocoapods next week. Stay tuned.

**Comment by alexandrenascimento** [comment]
Thanks a lot! I'll be waiting!

**Comment by robmontesinos** [comment]
Thank you for putting this library on Cocoapods!

I pulled the library into my project with the following:
pod 'VIMNetworking',  :git => "https://github.com/vimeo/VIMNetworking.git", :branch => "cocoa pod"

Got a compile error on VIMUser.h --> VIMModelObject.h not found.

There may be other files. This is the only error that appears.

**Comment by alfiehanssen** [comment]
I'll merge this to Dev and then master soon. We'll update the docs too. 

You also need to include the VIMModelObject pod and the AFNetworking pods. That should resolve your errors.

**Comment by robmontesinos** [comment]
Thank you @alfiehanssen - I'm blown away on how quick you have been responding. I'm looking forward to it. cheers!

**Comment by alfiehanssen** [comment]
Hey @robmontesinos, thank you! Happy to help. Keep us posted. This is my first time using cocoapods and given the complexity of our setup over here I'm sure there will be kinks to work out. Hopefully as a VIMNetworking consumer it's easy. 

I just podified the VIMObjectMapper, VIMVideoPlayer, VIMNetworking repos. So you should be good to go there. Will update the docs shortly.

**Comment by robmontesinos** [comment]
Hey @alfiehanssen - you're a ROCK STAR!! So imoressed. I can't wait. I thought it was going to be a week so I started working on a different project. I will definitely keep you posted. Have a great week and I hope that everything goes smooth. YOLO!!

**Comment by alfiehanssen** [comment]
Awesome, just pushed the final stuff to the dev branch. And updated README. Let us know if you have questions and feel free to submit pull requests :)

**Comment by robmontesinos** [comment]
Sorry to be a pain but the following is not working:

pod "AFNetworking", "~> 2.0"
target 'MyTarget' do
    pod 'VIMNetworking', '5.4.2'
end

target 'MyTarget' do
    pod 'VIMObjectMapper', '5.4.2'
end

Terminal kicks out the following:
### Error

```
Errno::EEXIST - File exists @ dir_s_mkdir - /Users/tico/iOS8/MyTarget/Pods/Target Support Files/Pods-MyTarget-AFNetworking

I tried removing AFNetworking from the podfile to no avail. Any help would be awesome

**Comment by robmontesinos** [comment]
This worked temporarily in terms of the app building

pod "AFNetworking", "~> 2.0"
pod 'VIMNetworking', :git => "https://github.com/vimeo/VIMNetworking.git", :branch => "cocoapod"
pod 'VIMObjectMapper', :git => "https://github.com/vimeo/VIMObjectMapper.git"
pod 'VIMVideoPlayer', :git => "https://github.com/vimeo/VIMVideoPlayer.git"

**Comment by alfiehanssen** [comment]
MyTarget is a placeholder to be replaced by the name of the target your are setting up the dependencies for. 

You just need to add dependencies for VIMNetworking, VIMObjectMapper and AFNetworking. To your relevant target in your pod file. 

pod 'VIMNetworking', '5.4.2'
pod 'VIMObjectMapper', '5.4.2'
pod 'AFNetworking', '2.5.4'

**Comment by robmontesinos** [comment]
Thanks Alfie. I did replace 'MyTarget' with my app target name - 'BarBook'. Sorry about not explaining that clearly. It still didn't work as:

pod "AFNetworking", "~> 2.0"
target 'BarBook' do
pod 'VIMNetworking', '5.4.2'
end

target 'BarBook' do
pod 'VIMObjectMapper', '5.4.2'
end

I have been using Cocoapods for a while now but I've never used the 'Target do - end' statement before.

Can I send you my Podfile?

**Comment by alfiehanssen** [comment]
Sure thing,

I'm brand new to Cocoapods,

I would think this would work:

target 'BarBook' do
pod 'VIMNetworking', '5.4.2'
pod 'VIMObjectMapper', '5.4.2'
pod "AFNetworking", "~> 2.0"
end

But am not sure if VIMNetworking will work with AF v2.0...

**Comment by alfiehanssen** [comment]
Can you try that and paste the full error output?

**Comment by alexandrenascimento** [comment]
It's not your fault, but just for information the VIMNetworking uses the version 2.5.3 of the AFNetworking and the RestKit uses the version 1.1.0. That's results in a conflit:

- `AFNetworking (~> 2.5.3)` required by `VIMNetworking/AFNetworking (5.4.2)`
- `AFNetworking (= 1.1.0)` required by `RestKit/Network (0.20.0)`

I'm looking a way to solve it...

**Comment by alfiehanssen** [comment]
Ahhh I see, I was under the impression that cocoapods would handle that for you, interesting. Keep us posted

**Comment by robmontesinos** [comment]
I added the following as you suggested:

target 'BarBook' do
pod 'VIMNetworking', '5.4.2'
pod 'VIMObjectMapper', '5.4.2'
pod "AFNetworking", "~> 2.0"
end

I got the following warning from Cocoapods:
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `BarBook` to `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.debug.xcconfig` or include the `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.debug.xcconfig` in your build configuration.

I got a build error: VIMVideoPlayerView.h - file not found

**Comment by alexandrenascimento** [comment]
@robmontesinos try just this:
target 'BarBook' do
pod 'VIMNetworking', '5.4.2'
end

The VIMNetworking dependencies will install the other pods automatically

**Comment by robmontesinos** [comment]
I will try. Just before your last post I tried the following and it worked with no messages or build errors:

pod 'VIMNetworking', '~>5.4.2'
pod 'VIMObjectMapper', '~>5.4.2'
pod 'AFNetworking', '~> 2.0'
pod 'VIMVideoPlayer', '~>5.4.2'

**Comment by robmontesinos** [comment]
@alexandrenascimento I just ran pod install with:

target 'BarBook' do
pod 'VIMNetworking', '5.4.2'
end

Cocoapods messages:
Removing VIMVideoPlayer

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `BarBook` to `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.debug.xcconfig` or include the `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.debug.xcconfig` in your build configuration.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `BarBook` to `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.release.xcconfig` or include the `Pods/Target Support Files/Pods-BarBook/Pods-BarBook.release.xcconfig` in your build configuration.

Scratching my head. Why is it necessary to include "target - do - end" ?

**Comment by robmontesinos** [comment]
this worked with no cocoa pods messages or build errors

pod 'VIMNetworking', '~>5.4.2'
pod 'VIMVideoPlayer', '~>5.4.2'

Thoughts?

**Comment by alfiehanssen** [comment]
VIMNetworking depends on VIMObjectMapper and AFNetworking.

But not VIMVideoPlayer. VIMVideoPlayer shouldn't be necessary if you just want to use VIMNetworking. Not sure why it's showing up there.

**Comment by robmontesinos** [comment]
@alfiehanssen Thank you Alfie - my Cocoapods issue seems to be resolved. I left VIMVideoPlayer in. Now to try to get this library to work using fetchWithRequestDescriptor:completionBlock: - I keep getting VIMServerResponse result: (null) - but that's a different issue. It's good to be working with the code. Outstanding library!

**Comment by alfiehanssen** [comment]
Thanks, glad it's up and running. Feel free to file issues / ask questions.

**Comment by robmontesinos** [comment]
Thank you @alfiehanssen - will do!
